# Replace the contents of `codechat_config.yaml` with this file to edit Linear Algebra
output_path: output/linear-algebra-web-instructor
args: "/conda/envs/sage/bin/python -m pretext build linear-algebra-web-instructor --xmlid {xml_id} --no-knowls"
project_type: PreTeXt
